# Regenerated after upgrading flyctl to new version
# fly.toml app configuration file generated for lisudoku-proxy on 2023-05-27T12:02:52+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lisudoku-proxy"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 35
    soft_limit = 30

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
